name: CI

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - run: cargo fmt --check
    # install dep
    - run: |
        sudo apt update && \
        sudo apt -y install \
        binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
        libgtk-4-1 libgtk-4-dev libadwaita-1-dev \
        libvulkan-dev vulkan-tools glslang-tools glslang-dev
      # (ubuntu 24.04) libvulkan-dev vulkan-tools glslang-tools glslc libshaderc-dev

    - run: cargo build --verbose
    - run: cargo test --verbose
    - run: cargo doc

    # host: x86_64-unknown-linux-gnu
    - run: cargo build --release -p pmse

    - run: |
        tar --zstd -cvf pmse_release_x86_64-unknown-linux-gnu.tar.zst \
        target/release/pmse
    - uses: actions/upload-artifact@v4
      with:
        name: pmse_release_x86_64-unknown-linux-gnu
        path: pmse_release_x86_64-unknown-linux-gnu.tar.zst

    # TODO
    # target: aarch64-unknown-linux-gnu
    # - run: rustup target add aarch64-unknown-linux-gnu

    # - run: cargo build --release --target aarch64-unknown-linux-gnu -p pmse
    #   env:
    #     CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
    #     CC_aarch64_unknown_linux_gnu: aarch64-linux-gnu-gcc
    #     CXX_aarch64_unknown_linux_gnu: aarch64-linux-gnu-g++

    # - run: |
    #     tar --zstd -cvf pmse_release_aarch64-unknown-linux-gnu.tar.zst \
    #     target/aarch64-unknown-linux-gnu/release/pmse
    # - uses: actions/upload-artifact@v4
    #   with:
    #     name: pmse_release_aarch64-unknown-linux-gnu
    #     path: pmse_release_aarch64-unknown-linux-gnu.tar.zst
